baseURL = "https://vishvAsa.github.io/vedAH/"
languageCode = "en-us"101_dasharathaniryANakathanam.md
title = "वेदे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/vedAH/edit/content/"
  contactLink = "https://github.com/vishvAsa/vedAH/issues/new"
  build_img = "https://github.com/vishvAsa/vedAH/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/vishvAsa/vedAH/actions/workflows/build.yml"
  fullSearchURL = "/full_search"
  env = "production"
  disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true